import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { redirect } from "next/navigation";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="items-center justify-center bg-[#0f172a] text-[#E2E8F0] ">
        <div className="flex flex-col items-center justify-center h-full w-full bg-[64748B]">
          {children}
        </div>
      </body>
    </html>
  );
}
